---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 8060

# Allow thymeleaf template changes to reload:
spring.thymeleaf.cache: false

# Zuul-proxied services can be found by calling /services/subject, /services/verb, etc.
zuul:
  prefix: /api
