---
---
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/git-jaav/ConfigData
          #searchPaths: ConfigData
          #"native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          #earchLocations: \\10.10.2.90\erpspring\WORKFLOW_TRACKING\CONFIG-CLOUD
          searchLocations: classpath:offline-repository/
          
  profiles:
    active: native 
              
server:
  port: 8001
